version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Build started on `date`
      - echo Building the webapp...
      - docker-compose run prod_build
      - echo Build completed on `date`
      - echo Pushing the webapp to S3...
      - aws s3 sync docker/build s3://phlask-beta-gcardona --acl public-read --delete