version: '3'
services:
  app:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - ".:/usr/src/app"
  prod_build:
    build: .
    entrypoint: npm run build
    volumes:
    - "./docker/build:/usr/src/app/build"