version: '3'
services:
  app:
    build: .
    ports:
    - "3000:3000"
    entrypoint: bash -c "yarn install && yarn start"
    volumes:
    - ".:/usr/src/app"
  prod_build:
    build: .
    entrypoint: yarn build
    volumes:
    - "./docker/build:/usr/src/app/build"